
project_id = "mxfhtujraqkcswtaxcns"

[api]
enabled = true
port = 54321

[db]
enabled = true
port = 54322

[studio]
enabled = true
port = 54323

[functions.gemini-interview]
verify_jwt = false

[functions.generate-certificate]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.voice-to-text]
verify_jwt = false

[functions.learning-service]
verify_jwt = false
