// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mxfhtujraqkcswtaxcns.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14Zmh0dWpyYXFrY3N3dGF4Y25zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MzQyODIsImV4cCI6MjA2MTUxMDI4Mn0.1vsPbsbqOvbmkI5EE_-Z0ZB5g89Qlrnfc8ugxoAH9RI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);